### ISSUE TITLE
`reprun`: Handle `clear all` dropping programs

### ISSUE THREAD

**Issue by bbdaniels** [worldbank/repkit#3]
Ensure that `reprun` doesn't break when the target file calls `clear all`, `clear *`, or equivalent. This may be solved by making sure the command is fully installed by the user but need to check. See 932ec9764d886bfb1752bf6e09dd955f9c5ec1c5 for a dicey implementation in the prior version -- Hopefully nothing like that will be necessary. (https://github.com/worldbank/ietoolkit/commit/932ec9764d886bfb1752bf6e09dd955f9c5ec1c5#diff-36d36e7ffbaaeb3a44fc03eb77b0e9f5347f491c7fcedb2a3f732315323ecb60)

**Comment by kbjarkefur** [comment]
`clear all` was no issue when the command was installed. I have included an test example that tests this in 24bd552d38b5a69de0b465b12e6553614eaca5a3. 

One important for our test file to handle this is to not load the command using `qui do "${ado_fldr}/reprun.ado"`. As that only loads the command in memory. This is not the best simulation of the user experience, as a user will have the command installed. Therefore, I have updated the test file to `net install` the package from the clone. The `adodown` workflow makes this easy as the `.pkg` file is kept up to date. See here:

https://github.com/dime-worldbank/repkit/blob/24bd552d38b5a69de0b465b12e6553614eaca5a3/src/tests/reprun/reprun.do#L22-L25

Now when we have `repado` I think all our test files should use this as `net install repkit, from("${src_fldr}") replace` creates a more relaistic test environment than `qui do "${ado_fldr}/reprun.ado"`. 

This `clear all` case is one example. But another example is that when we use `qui do "${ado_fldr}/reprun.ado"` all sub-commands, such as `reprun_recurse` is also made availible as the `ado` file behaves as an ado when executed with `do`.

**Comment by bbdaniels** [comment]
When I changed the `main.do` file to use `clear all` it broke. I will try to fix it.

**Comment by bbdaniels** [comment]
This appears to be resolved.

**Comment by bbdaniels** [comment]
@kbjarkefur I cannot run the test files with `clear all` in most recent code. Please review....

**Comment by bbdaniels** [comment]
Strangely, this is resolved by restarting Stata. Perhaps there is something not fully reset if `repado` is run more than once? This may be an issue with that command instead....
