### ISSUE TITLE
`reprun`: Sub do-files that don't have the `.do` file extension cause an error

### ISSUE THREAD

**Issue by luisesanmartin** [worldbank/repkit#31]
Tried `reprun` with a main do-file with the following line:

```
do "$dos/01_01_Matching_Harmonize_HBS"
```

and it returned an error saying :

```
`file C:/Users/wb532468/OneDrive - WBG/Rep-checks/FY24/RR_BGR_2024_93/code\Do/01_01_Matching_Harmonize_HBS not
    found
r(601);
```

but then I added the `.do` extension in the sub do-file and it worked. I think it would be better if it recognized that the sub do-file just doesn't have the extension

**Comment by bbdaniels** [comment]
To clarify -- the issue here is that there is no extension in the code, not in the file, right?

**Comment by yukinko-iwasaki** [comment]
Yes. In my test case, the files did have the .do extentions. 
But the code did not specify the do extensions when trying to refer them.
